openapi: 3.0.3
info:
  title: Weather Data API
  description: API for retrieving real-time weather data at a specified location.
  version: 1.0.0
  contact:
    name: Weather API Provider

servers:
  - url: https://api.weatherprovider.com

paths:
  /weather:
    get:
      summary: Get weather data
      description: Retrieve real-time weather data for a specific location.
      operationId: getWeatherData
      parameters:
        - in: query
          name: location
          schema:
            type: string
          required: true
          description: Location for which to retrieve weather data (latitude,longitude).
        - in: query
          name: units
          schema:
            type: string
            enum: [metric, imperial]
          description: Units for temperature (e.g., metric for Celsius).
      responses:
        '200':
          description: Weather data response
          content:
            application/json:
              schema:
                type: object
                properties:
                  temperature:
                    type: number
                    description: Current temperature.
                  conditions:
                    type: string
                    description: Current weather conditions (e.g., clear, rain).
                  delay_factor:
                    type: integer
                    description: Suggested delay in minutes due to weather.
                  status:
                    type: string
                    description: Status of the weather data request.
